FROM maven:3.8.6
WORKDIR /usr/src/app/
COPY . .
ENV MAIL_SENDER_HOST=$MAIL_SENDER_HOST
ENV MAIL_SENDER_PORT=$MAIL_SENDER_PORT
ENV MAIL_SENDER_PASSW=$MAIL_SENDER_PASSW
ENV MAIL_SENDER_USERNAME=$MAIL_SENDER_USERNAME
WORKDIR /usr/src/app/WebFlux/Mail
RUN mvn clean package
EXPOSE 8080
CMD java -jar ./target/Mail-0.0.1-SNAPSHOT.jar

